name: All End-to-End Tests

on:
  push:

jobs:
  cypress-regression-test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run regression tests
      - name: Run Cypress regression tests
        uses: cypress-io/github-action@v6
        with: 
          command: npm run only-regression-test

  cypress-smoke-test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run smoke tests
      - name: Run Cypress smoke tests
        uses: cypress-io/github-action@v6
        with: 
          command: npm run only-regression-test
